// Anchored, EOL-preserving source edits that make the armoured Reaver the warrior's production
// body: the player_warrior VisualDef (url, matte, no KayKit accessories, no kit shield), the
// CREDITS rows for both generated bodies, the library tests that pinned knight.glb to the
// warrior, and the slice harness default. Every anchor must match exactly once in its scope
// or the script throws. Re-running is a no-op.
const fs = require('node:fs');
const path = require('node:path');

const ROOT = 'C:/Dev/simpleMMO/reference/world-of-claudecraft';
const abs = (p) => path.join(ROOT, p);

function readLines(file) {
  const text = fs.readFileSync(abs(file), 'utf8');
  const eol = text.includes('\r\n') ? '\r\n' : '\n';
  return { eol, lines: text.split(eol) };
}
function writeLines(file, { eol, lines }) {
  fs.writeFileSync(abs(file), lines.join(eol));
}
function onlyIndex(lines, pred, label, from = 0, to = lines.length) {
  const hits = [];
  for (let i = from; i < to; i++) if (pred(lines[i])) hits.push(i);
  if (hits.length !== 1) throw new Error(`${label}: expected one anchor, found ${hits.length}`);
  return hits[0];
}
/** Bounds of the block opened by `openLine` and closed by the first `closeLine` after it. */
function blockRange(lines, openLine, closeLine, label) {
  const open = onlyIndex(lines, (l) => l === openLine, `${label} open`);
  const close = lines.findIndex((l, i) => i > open && l === closeLine);
  if (close < 0) throw new Error(`${label}: no "${closeLine}" after "${openLine}"`);
  return [open, close];
}
function replaceLine(file, from, to, scope) {
  const doc = readLines(file);
  if (doc.lines.includes(to)) return console.log(`${file}: already has "${to.trim()}", skipped`);
  const [a, b] = scope
    ? blockRange(doc.lines, scope[0], scope[1], `${file} scope`)
    : [0, doc.lines.length];
  const at = onlyIndex(doc.lines, (l) => l === from, `${file} line "${from.trim()}"`, a, b);
  doc.lines[at] = to;
  writeLines(file, doc);
  console.log(`${file}: replaced "${from.trim()}"`);
}
function removeLine(file, line, scope) {
  const doc = readLines(file);
  const [a, b] = scope
    ? blockRange(doc.lines, scope[0], scope[1], `${file} scope`)
    : [0, doc.lines.length];
  const hits = [];
  for (let i = a; i < b; i++) if (doc.lines[i] === line) hits.push(i);
  if (hits.length === 0) return console.log(`${file}: "${line.trim()}" already gone, skipped`);
  if (hits.length > 1)
    throw new Error(`${file}: "${line.trim()}" found ${hits.length} times in scope`);
  doc.lines.splice(hits[0], 1);
  writeLines(file, doc);
  console.log(`${file}: removed "${line.trim()}"`);
}
function insertAfterLine(file, anchor, newLines, scope) {
  const doc = readLines(file);
  const [a, b] = scope
    ? blockRange(doc.lines, scope[0], scope[1], `${file} scope`)
    : [0, doc.lines.length];
  if (doc.lines.slice(a, b).some((l) => newLines.includes(l)))
    return console.log(`${file}: insertion present, skipped`);
  const at = onlyIndex(doc.lines, (l) => l === anchor, `${file} anchor "${anchor.trim()}"`, a, b);
  doc.lines.splice(at + 1, 0, ...newLines);
  writeLines(file, doc);
  console.log(`${file}: inserted ${newLines.length} line(s) after "${anchor.trim()}"`);
}

// 1. player_warrior: the armoured Reaver body on the hero skeleton.
const MANIFEST = 'src/render/characters/manifest.ts';
const WARRIOR = ['  player_warrior: swims({', '  }),'];
replaceLine(
  MANIFEST,
  // biome-ignore lint/suspicious/noTemplateCurlyInString: inserted source text, the placeholder must land verbatim
  '    url: `${PLAYERS}/knight.glb`,',
  // biome-ignore lint/suspicious/noTemplateCurlyInString: inserted source text, the placeholder must land verbatim
  '    url: `${PLAYERS}/hero_warrior_leather.glb`,',
  WARRIOR,
);
insertAfterLine(
  MANIFEST,
  // biome-ignore lint/suspicious/noTemplateCurlyInString: inserted source text, the placeholder must land verbatim
  '    url: `${PLAYERS}/hero_warrior_leather.glb`,',
  [
    '    // The simpleMMO hero: the Horned Reaver in his Ninebend starter kit, generated by the',
    '    // asset pipeline (concept_dress.mjs on the body plate, Tripo image-to-model, rig-manual',
    '    // onto the hero skeleton). It carries the KayKit joint names and the knight clip library',
    '    // re-baked to its proportions, so the knight clip donors below still apply. Authored PBR',
    '    // reads as gloss on leather and skin under the scene rig, hence matte.',
  ],
  WARRIOR,
);
insertAfterLine(MANIFEST, '    height: HUMANOID_H,', ['    matte: true,'], WARRIOR);
removeLine(
  MANIFEST,
  "    show: ['Knight_Helmet', 'Knight_Cape'], // v2 knight dropped the built-in Badge_Shield mesh",
  WARRIOR,
);
// The Reaver carries no shield (docs/design/art-styles hero brief); no authored offhand and no
// live offhand slot until the simpleMMO gear system decides what the left hand shows.
// biome-ignore lint/suspicious/noTemplateCurlyInString: inserted source text, the placeholder must land verbatim
removeLine(MANIFEST, "      { url: `${WEAPONS}/shield_round.glb`, bone: 'handslot.l' },", WARRIOR);
removeLine(MANIFEST, '    offhandSlot: 1,', WARRIOR);

// 2. CREDITS rows for both generated player bodies.
insertAfterLine(
  'CREDITS.md',
  '| Generated creature model + animations (river_drowned) | World of ClaudeCraft | Project-generated via scripts/asset_pipeline (Tripo AI 3D, auto-rig + preset retargets) | Project asset | With the project only |',
  [
    '| Generated player body (hero_warrior, the Horned Reaver) | World of ClaudeCraft | Project-generated via scripts/asset_pipeline (gpt-image concept, Tripo AI 3D image-to-model, proportion-fit rig onto the KayKit Rig_Medium skeleton with the knight clip library re-baked) | Project asset | With the project only |',
    '| Generated player body (hero_warrior_leather, the Reaver in his Ninebend starter kit) | World of ClaudeCraft | Project-generated via scripts/asset_pipeline (concept_dress.mjs gpt-image edit of the body plate, Tripo AI 3D image-to-model, rig-manual onto the hero skeleton) | Project asset | With the project only |',
  ],
);

// 3. Library tests that pinned knight.glb to the warrior.
replaceLine(
  'tests/asset_pipeline.test.ts',
  "    expect(map.get('models/chars/players/knight.glb')).toContain('player_warrior');",
  "    expect(map.get('models/chars/players/hero_warrior_leather.glb')).toContain('player_warrior');",
);
replaceLine(
  'tests/asset_pipeline.test.ts',
  "    expect(knight.registration.visualKeys).toContain('player_warrior');",
  "    expect(knight.registration.visualKeys).toContain('npc_knight');",
);

// 4. Slice harness: the wired body is the default; HERO_URL stays an override.
replaceLine(
  'scripts/slice_capture.mjs',
  "const HERO_URL = process.env.HERO_URL ?? 'models/chars/players/hero_warrior.glb';",
  "const HERO_URL = process.env.HERO_URL ?? '';",
);
replaceLine(
  'scripts/slice_capture.mjs',
  '//   HERO_URL=models/chars/players/hero_warrior.glb  (empty string = keep the knight)',
  '//   HERO_URL=models/chars/players/<body>.glb  (default: the wired player_warrior body)',
);
